#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

# Firmware
TARGET_VENDOR_FIRMWARE_QCOM_COPY :=

LOCAL_FIRMWARE_GPU_A3XX := \
    a300_pfp.fw \
    a300_pm4.fw
LOCAL_FIRMWARE_GPU_A5XX := \
    a530_pfp.fw \
    a530_pm4.fw
ifneq ($(filter qcm2150 qm215 msm8917 msm8920,$(TARGET_QCOM_SOC)),)
TARGET_VENDOR_FIRMWARE_QCOM_COPY += $(LOCAL_FIRMWARE_GPU_A3XX)
else ifneq ($(filter msm8937 msm8940 sdm429 sdm439,$(TARGET_QCOM_SOC)),)
TARGET_VENDOR_FIRMWARE_QCOM_COPY += $(LOCAL_FIRMWARE_GPU_A5XX)
else
TARGET_VENDOR_FIRMWARE_QCOM_COPY += \
    $(LOCAL_FIRMWARE_GPU_A3XX) \
    $(LOCAL_FIRMWARE_GPU_A5XX)
endif
